@Api_HostAddress = http://localhost:1337

@BobToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiI3Nzg5ZjQyZiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTcyNTQ2NjM3MCwiZXhwIjoxNzMzMzI4NzcwLCJpYXQiOjE3MjU0NjYzNzEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.zZ9PAWkk47KeJgyNfscaMRLSSjZpgEYszHdkRMx6Mz8
@SueToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBhb2wuY29tIiwic3ViIjoic3VlQGFvbC5jb20iLCJqdGkiOiI3MTkzMzU2NiIsInJvbGUiOlsiU29mdHdhcmVDZW50ZXIiLCJTb2Z0d2FyZUNlbnRlckFkbWluIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTcyNTQ2NzE5NCwiZXhwIjoxNzMzMzI5NTk0LCJpYXQiOjE3MjU0NjcxOTUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.3Yek8HIRmCU5dkC7vUqBYCEAKfWNeod9IMoav8DFb_o

POST {{Api_HostAddress}}/catalog/microsoft/software
Content-Type: application/json

{
  "name": "Some Name",
  "description": "Some Description"
  
}
###
# MAke a get request to vendors with an authorized user (Employee)

GET {{Api_HostAddress}}/vendors
Authorization: {{BobToken}}


###
# Should get a 401 without a valid token
GET {{Api_HostAddress}}/vendors


### Catalog

# Adding an item without a token gives a 401
POST {{Api_HostAddress}}/vendors
Content-Type: application/json

{
  "name": "Oracle"
}

### 
# You have to be a software center admin 403

POST {{Api_HostAddress}}/vendors
Content-Type: application/json
Authorization: {{BobToken}}

{
  "name": "Oracle"
}


### You can do this if you are software center admin

POST {{Api_HostAddress}}/vendors
Content-Type: application/json
Authorization: {{SueToken}}

{
  "name": "Oracle"
}
